### ISSUE TITLE
output format?

### ISSUE THREAD

**Issue by owensgl** [russcd/proximity_ligation_inversion_mapping#1]
Hi,

Can you describe what the format of the output is? I've tried running it with bootstraps and I got the following output:
Boostrapped Confidence Intervals:       [ 6041341.475  7859375.   ]     [  6187500.    10676053.65]
I'm not entirely sure what that means. 

Thanks,
Greg

**Comment by russcd** [comment]
Hi Greg, 

This should be the [2.5L and 97.5L] [2.5H and 97.5H]. 

Where 2.5L-97.5L is the 95% CI for the lower bound, and 2.5H-97.5H is the CI for the upper bound. I'll modify the manual to make that clearer. Thanks for bringing it up. 

That interval is pretty big, so I suspect something is not working quite right. If you're willing to send me your data or just input file, I can take a look to see if there's a bug or something obviously wrong. 

Russ

**Comment by russcd** [comment]
The script has been updatd to make the output format clearer. Thank you for bringing this to my attention.
